### ISSUE TITLE
More than one key on each namespace returns error

### ISSUE THREAD

**Issue by sanchezandoni** [kawan16/mithril-storage#3]
If you try to do:

var myStorage = mx.storage("myStorage", mx.COOKIE_STORAGE);

myStorage.set("myFirstKey", "myFirstValue");
myStorage.set("mySecondKey", "mySecondValue");

myStorage.get()

it returns an error:

Uncaught SyntaxError: Unexpected token ;

anyway to fix this??

**Comment by kawan16** [comment]
Hi,

I guess it is because you call the method "get" without specifying a key ?? The method expects to be  called in this way:

`
myStorage.get( "myFirstKey" ); // Should return myFirstValue
myStorage.get( "mySecondKey" ); // Should return mySecondValue
` 

Let me know if the issue still occurs

**Comment by sanchezandoni** [comment]
already tried it...
it returns "Uncaught SyntaxError: Unexpected token ;(…)" too.
i tried it on the Demo page, using Google Chrome´s console.
Here's the screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/1240478/12699425/bd70316e-c7ba-11e5-8830-02b4755e0a6d.png)

**Comment by kawan16** [comment]
Oh yes, you're right ! @jun0205 fixed this a month ago ( thanks ! ) but didn't take the time to merge it. Now it's done and should better work.
